# Site settings
title: "Asaph Tinoco - Data & Cloud Engineer"
markdown: GFM
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

tagline: "Cloud, Data, and Engineering Solutions"
description: "Portfolio and blog of Asaph Tinoco, specializing in data engineering, cloud architecture, and technical solutions."