# Site settings
title: "Asaph Tinoco - Data & Cloud Engineer"
tagline: "Cloud, Data, and Engineering Solutions"
description: "Portfolio and blog of Asaph Tinoco, specializing in data engineering, cloud architecture, and technical solutions. I am also a crypto enthusiast."

logo: /assets/images/logo.jpeg
markdown: GFM
content_width: 1200
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
